version: '2'
services:
  releaseserver-web:
    container_name: releaseserver-web
    build: .
    environment:
      APP_USERNAME:
      APP_PASSWORD:
      DB_HOST:
      DB_PORT:
      DB_USERNAME:
      DB_NAME:
      DB_PASSWORD:
      TOKEN_SECRET:
      APP_URL:
      ASSETS_PATH:
    depends_on:
      - releaseserver-db
    expose:
      - '80'
    networks:
      - proxy_nw
      - releaseserver
    entrypoint: ./scripts/wait.sh releaseserver-db:5432 -- npm start
    volumes:
      - ./releases:/usr/src/electron-release-server/releases
  releaseserver-db:
    container_name: releaseserver-db
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    expose:
      - "5432"
    networks:
      - releaseserver
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:

networks:
  proxy_nw:
    external: true
  releaseserver:
